trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Deploy_VM
  displayName: "Deploy VM with Terraform"
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pip install ansible
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<Your-Azure-Service-Connection>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
          terraform init
          terraform plan -out=tfplan
          terraform apply "tfplan"

- job: Configure_Docker
  displayName: "Configure Docker and Deploy HTML"
  dependsOn: Deploy_VM
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<Your-Azure-Service-Connection>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          ansible-playbook -i $(terraform output -raw public_ip_address), -u azureuser --private-key <path_to_ssh_key> ansible/deploy_docker.yml


