- name: Set up Docker and deploy HTML in Docker container
  hosts: all
  become: true
  tasks:

    - name: Update and install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Create directory for HTML file
      file:
        path: /home/azureuser/html
        state: directory
        owner: azureuser
        mode: '0755'

    - name: Create a simple HTML file
      copy:
        dest: /home/azureuser/html/index.html
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body><h1>Hello from Docker Container!</h1></body>
          </html>

    - name: Run Nginx container with HTML file
      docker_container:
        name: my_nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /home/azureuser/html:/usr/share/nginx/html


